initial flow for pricing service subscription
WalletSphere/crypto-pricing-service pull request #1
Opened 2023-12-15 20:08 UTC by mkhomishchak

added whitebit ws connectivity 
added flow for users subscriptions and message handling after that
handling whitebit connections is implemented in a way that we will follow only currencies that are followed by our users

2023-12-16 00:47 UTC, COCONUTmkII requested changes
First things first, you did a great job bruv. Sorry, I don't understand your business domain here well that's why I cannot add more useful architecture advices. 

In addition I like your simplicity in the code, also your approach. ❤️ 

But you can still improve it according to my comments. If you disagree with something, suit yourself, I'm also could be wrong :3

Also you're using spring boot for this application or microservice, I don't know what it will be in the future. Thus you can take a look at [Ktor](https://ktor.io) which can be a good choice here.

P.S. Try to always keep EoL (end of line) in each file to make github more happy about it because sometimes when you push new code github can show your changes wrong.

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/config/WebSocketConfig.kt
> +    override fun registerWebSocketHandlers(registry: WebSocketHandlerRegistry) {
Use expression body here

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/WhiteBitWebSocketIntegrationWebSocketService.kt
> +        }
forEach and if statement there? Why not `any`?

`shouldReloadWsConnection = tickers.any { addNewTickerOrAccountAsSubscriber(it, accountId) }`

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/WhiteBitWebSocketIntegrationWebSocketService.kt
> +    override fun onFailure(webSocket: WebSocket, t: Throwable, response: Response?) = t.printStackTrace()
I understand that you're using printstacktrace here just for now, but don't forget later to change it to kotlin logger ❤️

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/WhiteBitWebSocketIntegrationWebSocketService.kt
> +        }
Looks not too consice. Better to wrap it vice versa

```
if (method == "market_update") {
        val ticker = getTickerFromResp(this)
        notifyAccounts(this, ticker)
    }
```

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/WhiteBitWebSocketIntegrationWebSocketService.kt
> +        return update.params.firstOrNull()?.toString()?.split("_")?.get(0).orEmpty()
Firstly, expression body here.
Secondly, you can use substringBefore here to achieve the same result, but in a more readable way:

`private fun getTickerFromResp(update: WhiteBitWSMarketResp): String =
    update.params.firstOrNull()?.toString()?.substringBefore("_").orEmpty()`

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/WhiteBitWebSocketIntegrationWebSocketService.kt
> +    private fun notifyAccounts(update: WhiteBitWSMarketResp, ticker: String) {
Expression body

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/WhiteBitWebSocketIntegrationWebSocketService.kt
> +    private fun notifyAccountsForTicker(accountsToBeNotified: MutableList<Long>, update: WhiteBitWSMarketResp) {
Expression body

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/WhiteBitWebSocketIntegrationWebSocketService.kt
> +    override fun onOpen(webSocket: WebSocket, response: Response) {
Expression body

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/mapper/WsResponseMapper.kt
> +    }
Instead of doing all of this, better to use reified construction to achieve the same result without ugly casting and also better performance:

```
inline fun <reified T> mapRespToMarketUpdate(json: String): T =
    gson.fromJson(json, object : TypeToken<T>() {}.type)
```

I already explained you the concepts of reified and inline, but we can talk after 1v1 if you have a questions about it

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/mapper/WsResponseMapper.kt
> +    }
In addition, you can use extension function to create a concise mapper here for Gson library (god forgive me) or directly in your return type if you want:

```
inline fun <reified T> Gson.fromJson(json: String): T =
    this.fromJson(json, object : TypeToken<T>() {}.type)
```

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/mapper/WsResponseMapper.kt
> +    val gson = Gson()
This can be moved to canonical constructor because you're already using Component here

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/mapper/WsResponseMapper.kt
> +class WsResponseMapper {
By the way, generally, in Kotlin mappers are optional because we already have extension functions here. If you want you can even remove the class with component annotation and create an object or empty file and just use your mapper there if your business logic allows you to do that

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/ws/CryptoPriceWebsocketHandler.kt
> +    }
If I understood your business logic here correctly, you can even simplify this:

```
override fun handleTextMessage(session: WebSocketSession, message: TextMessage) {
        val json = JsonParser.parseString(message.payload).asJsonObject
        val method = json["method"].asString

        if (method == "subscribe_market") {
            val accountId = json["accountId"].asLong
            val exchanger = CryptoExchanger.valueOf(json["exchanger"].asString)
            val tickers = json["tickers"].asJsonArray.map { it.asString }

            sessionMappingService.registerSession(session, accountId)
            webSocketService.subscribe(accountId, exchanger, tickers)
        }
    }
    ```

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/ws/SessionMappingService.kt
> +        sessions[session.id] = session
I think using simple put here would be better:

`.put(session.id, session)`

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/ws/SessionMappingService.kt
> +    fun getSession(accountId: Long): WebSocketSession? = sessionMap[accountId]?.values?.toList()?.get(0);
You are using toList here with nullable check and after 'get(0)' which would return null. Thus, you can use here 
simple firstOrNull method, bruv.

`fun getSession(accountId: Long): WebSocketSession? =
    sessionMap[accountId]?.values?.firstOrNull()`

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/ws/SessionMappingService.kt
> +    }
Good progress to use kotlin scope functions ❤️ 

But don't forget to read about another ones :3 

`fun sendMessageToSession(accountId: Long, message: String) =
    getSession(accountId)?.takeIf { it.isOpen }?.sendMessage(TextMessage(message))`

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/ws/WebSocketService.kt
> +interface WebSocketService {
Mark this interface with `fun` keyword. I'm not judging here though, but this is just a good practice ;3

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/ws/WebSocketServiceImpl.kt
> +    override fun subscribe(accountId: Long, exchanger: CryptoExchanger, tickers: List<String>) {
Expression body here pupsik

2023-12-16 00:47 UTC, COCONUTmkII commented on src/main/kotlin/com/khomishchak/cryptopricingservice/model/integration/CryptoExchanger.kt
> +enum class CryptoExchanger {
Just letting you know here. Sometimes, sealed classes are better in specific cases. Sealed classes in kotlin are more powerful than in ~yebanaya~ java. You can easily find information about them in google bruv

2023-12-16 08:58 UTC, mkhomishchak commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/WhiteBitWebSocketIntegrationWebSocketService.kt
> +        }
any will not iterate through whole list, once it will find at least 1 call of addNewTickerOrAccountAsSubscriber() that returns true it will stop iterating, but we need to go through all of the tickers

2023-12-16 09:10 UTC, mkhomishchak commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/integration/exchangers/white_bit/WhiteBitWebSocketIntegrationWebSocketService.kt
> +    override fun onOpen(webSocket: WebSocket, response: Response) {
is this possible if I have 2 separate operations? 
`this.webSocket = webSocket and
``logger.info("established connection with WhiteBit WS successfully!")`
i can use `run {  }` block, but in my opinion it will reduce readability

2023-12-16 13:28 UTC, DJmoster approved these changes

2023-12-17 14:06 UTC, mkhomishchak commented on src/main/kotlin/com/khomishchak/cryptopricingservice/model/integration/CryptoExchanger.kt
> +enum class CryptoExchanger {
in my case I need just fixed set of exchangers, in this scenario enum should be fine

2023-12-17 14:06 UTC, mkhomishchak commented on src/main/kotlin/com/khomishchak/cryptopricingservice/config/WebSocketConfig.kt
> +    override fun registerWebSocketHandlers(registry: WebSocketHandlerRegistry) {
not sure I can do so in here
origin fun expects to return `Unit`, but overriding it by expression body will cause that `WebSocketHandlerRegistration` will be returned

2023-12-17 14:06 UTC, mkhomishchak commented on src/main/kotlin/com/khomishchak/cryptopricingservice/service/ws/SessionMappingService.kt
> +        sessions[session.id] = session
this sessionMap is a map that contains accountId as a key, and properties of session as a value into separate map, if user didn't have a session before now, we will create a new map for him `sessionMap.computeIfAbsent(accountId) { ConcurrentHashMap() }`
and then populate with session data `sessions[session.id] = session`

2023-12-18 09:51 UTC, merged